name: clingo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      manylinux1_gcc: ${{ steps.filter.outputs.manylinux1_gcc }}
      manylinux1_mirrors: ${{ steps.filter.outputs.manylinux1_mirrors }}
      manylinux2014: ${{ steps.filter.outputs.manylinux2014 }}
      centos6: ${{ steps.filter.outputs.centos6 }}
    steps:
    - uses: actions/checkout@v2
      if: ${{ github.event_name == 'push' }}
      with:
        fetch-depth: 0
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # See https://github.com/dorny/paths-filter/issues/56 for the syntax used below
        filters: |
          manylinux1_gcc:
          - './clingo/Dockerfile.manylinux1_gcc9'
          - './clingo/packages.yaml'
          manylinux1_mirrors:
          - './clingo/Dockerfile.manylinux1_mirrors'
          - './clingo/scripts/create_binary_mirror.sh'
          - './clingo/scripts/install_clingo.py'
          - './clingo/scripts/bootstrap_clingo_manylinux1.sh'
          - './spack/patches/spack_rhel5.patch'
          manylinux2014:
          - './clingo/Dockerfile.manylinux2014'
          - './clingo/scripts/create_binary_mirror.sh'
          - './clingo/scripts/install_clingo.py'
          - './clingo/scripts/bootstrap_clingo_manylinux2014.sh'
          - './spack/patches/spack_buildx.patch'
          centos6:
          - './clingo/Dockerfile.centos6'
          - './clingo/patches/centos6/*'
          - './clingo/scripts/centos6/*'

  manylinux_gcc:
    runs-on: ubuntu-latest
    needs: [ changes ]
    env:
      PLATFORM: x86_64
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      # Setup tags to be used for docker images
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/manylinux1_gcc9_x86_64

      # Login to Github Packages
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/setup-buildx-action@v1

      # Build and eventually push to registry
      - uses: docker/build-push-action@v2
        # Build and push only if the Dockerfile changed
        if: ${{ needs.changes.outputs.manylinux1_gcc == 'true' }}
        with:
          file: ./clingo/Dockerfile.manylinux1_gcc9
          platforms: linux/amd64
          pull: ${{ github.event_name == 'pull_request' }}
          push: true
          tags: ghcr.io/alalazo/manylinux1_gcc9_x86_64:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

  manylinux1_mirrors:
    runs-on: ubuntu-latest
    needs: [ changes, manylinux_gcc ]
    env:
      PLATFORM: x86_64
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      # Setup tags to be used for docker images
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/manylinux1_mirrors

      # Login to Github Packages
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/setup-buildx-action@v1

      # Build and eventually push to registry
      - uses: docker/build-push-action@v2
        if: ${{ needs.changes.outputs.manylinux1_mirrors == 'true' }}
        with:
          file: ./clingo/Dockerfile.manylinux1_mirrors
          platforms: linux/amd64
          pull: ${{ github.event_name == 'pull_request' }}
          push: true
          tags: ghcr.io/alalazo/manylinux1_mirrors_x86_64:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

  upload-x86-64:
    runs-on: ubuntu-latest
    needs: [ manylinux1_mirrors ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          . ./clingo/scripts/copy_mirror_manylinux1.sh
      - uses: actions/upload-artifact@v2
        with:
          name: clingo_binary_mirror
          path: binary-mirror

  macos_clingo:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          brew install bison
          export PATH="/usr/local/opt/bison/bin:$PATH"
          git clone https://github.com/spack/spack.git spack-src
          . spack-src/share/spack/setup-env.sh
          spack external find --not-buildable cmake bison
          spack python clingo/scripts/install_clingo.py
          mkdir -p binary-mirror
          spack buildcache create -d $PWD/binary-mirror -a -u -f clingo-bootstrap
      - uses: actions/upload-artifact@v2
        with:
          name: clingo_binary_mirror
          path: binary-mirror

  manylinux2014:
    runs-on: ubuntu-latest
    needs: [ changes ]

    steps:
      - uses: actions/checkout@v2

      # Setup tags to be used for docker images
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/manylinux2014_mirrors

      # Login to Github Packages
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/setup-qemu-action@v1
        id: qemu
        with:
          platforms: linux/ppc64le,linux/arm64

      - uses: docker/setup-buildx-action@v1

      # Build and eventually push to registry
      - uses: docker/build-push-action@v2
        # Build and push only if the Dockerfile changed
        if: ${{ needs.changes.outputs.manylinux2014 == 'true' }}
        with:
          file: ./clingo/Dockerfile.manylinux2014
          platforms: linux/arm64,linux/ppc64le
          pull: ${{ github.event_name == 'pull_request' }}
          push: true
          tags: ghcr.io/alalazo/manylinux2014_mirrors:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

  upload-arm64-ppc64le:
    runs-on: ubuntu-latest
    needs: [ manylinux2014 ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          . ./clingo/scripts/copy_mirror_manylinux2014.sh
      - uses: actions/upload-artifact@v2
        with:
          name: clingo_binary_mirror
          path: |
            binary-mirror

  centos6:
    runs-on: ubuntu-latest
    needs: [ changes ]
    env:
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      # Setup tags to be used for docker images
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/centos6_x86_64

      # Login to Github Packages
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/setup-buildx-action@v1

      # Build and eventually push to registry
      - uses: docker/build-push-action@v2
        if: ${{ needs.changes.outputs.centos6 == 'true' }}
        with:
          file: ./clingo/Dockerfile.centos6
          platforms: linux/amd64
          pull: ${{ github.event_name == 'pull_request' }}
          push: true
          tags: ghcr.io/alalazo/centos6_x86_64:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

  upload-centos6:
    runs-on: ubuntu-latest
    needs: [ centos6 ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          . ./clingo/scripts/centos6/copy_mirror.sh
      - uses: actions/upload-artifact@v2
        with:
          name: clingo_binary_mirror
          path: binary-mirror

  clingo_json:
    runs-on: ubuntu-latest
    needs: [ upload-arm64-ppc64le, upload-x86-64, macos_clingo, upload-centos6 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/download-artifact@v2
        with:
          name: clingo_binary_mirror
      - run: |
          pip install ruamel.yaml
          python clingo/scripts/clingo_json.py
      - uses: actions/upload-artifact@v2
        with:
          name: clingo_manifest
          path: |
            clingo.json
