name: "GnuPG and OpenSSL"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86_64_mirrors:
    runs-on: ubuntu-latest
    env:
      PLATFORM: x86_64
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      # Setup tags to be used for docker images
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/gnupg_openssl_x86_64

      # Login to Github Packages
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/setup-buildx-action@v1

      # Build and eventually push to registry
      - uses: docker/build-push-action@v2
        with:
          file: ./gnupg_openssl/Dockerfile.x86_64
          platforms: linux/amd64
          pull: ${{ github.event_name == 'pull_request' }}
          load: true
          push: true
          tags: ghcr.io/alalazo/gnupg_openssl_x86_64:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
      - run: |
          . ./gnupg/copy_mirror_x86_64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: gnupg_binary_mirror
          path: binary-mirror
